# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dataverse_visualize',
                'doc_host': 'https://nakamura196.github.io',
                'git_url': 'https://github.com/nakamura196/dataverse_visualize',
                'lib_path': 'dataverse_visualize'},
  'syms': { 'dataverse_visualize.core': { 'dataverse_visualize.core.CoreClient': ('core.html#coreclient', 'dataverse_visualize/core.py'),
                                          'dataverse_visualize.core.CoreClient.__init__': ( 'core.html#coreclient.__init__',
                                                                                            'dataverse_visualize/core.py'),
                                          'dataverse_visualize.core.CoreClient.visualize_data': ( 'core.html#coreclient.visualize_data',
                                                                                                  'dataverse_visualize/core.py')}}}
